#!/bin/sh
#
#

TABLE="CREATE TABLE tickets(id INTEGER PRIMARY KEY, info TEXT, owner VARCHAR(32), created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, done BOOLEAN, deleted BOOLEAN);"
sqlite3 -line ticketblaster.db "$TABLE"
