#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Simple launcer program for the T I C K E T B L A S T E R.
#
# Just execute to see launcher options
#
# See README.md for more info
#
#
# MIT License
# author: Alexander Schüssler <alex@xalx.net>
import sys
import getopt
from ticketblaster import bot
from ticketblaster import wsgi
from multiprocessing import Process

def usage(Exit):
  usage = "tblaster -s <server> -c <channel> -b <bot> -p <port>"
  print usage
  sys.exit(Exit)

# Main initiatior of the ticketblaster bot
def main(argv):
  server  = ""
  channel = "bob"
  botnick = "bob"
  port    = 6667
  try:
    opts, args = getopt.getopt(argv,"hs:c:b:p::",["server=","channel=","bot=","port="])
  except getopt.GetoptError:
    usage(2)
  for opt, arg in opts:
    if opt == "-h":
      usage(0)
    elif opt in ("-s", "--server"):
      server = arg
    elif opt in ("-c", "--channel"):
      channel = arg
    elif opt in ("-b", "--bot"):
      botnick = arg
    elif opt in ("-p", "--port"):
      port = arg
  if server == "":
    usage(2)

  bot_proc  = Process(target=bot.loop,
                      args=(server, int(port), "#"+channel, botnick))
  wsgi_proc = Process(target=wsgi.server)
  bot_proc.start()  # Launch Bot (IRC bot interface)
  wsgi_proc.start() # Launch WSGI (Web interface)

if __name__ == "__main__":
  main(sys.argv[1:])
